insert into categories (category_name) values ('Cymbals');

insert into products (category_id, product_name, price, quantity_remaining, description, image) values ('1', 'Meinl Byzance Medium Ride', '419.99', '25', 'Their hand hammered and lathed surfaces with warm sounds and selection of models may be rooted in tradition, but MEINL Byzance cymbals are the ultimate choice when it comes to modern versatility. Every Byzance model is hand hammered into shape by cymbal artisans in Turkey, giving each cymbal its own unique and colorful voice. The overall presence that MEINL Byzance delivers is dark, buttery warmth that flows around crisp definition. The Byzance 22-inch medium ride has a balanced, shimmering stick response with a defined ping and a blend of bright overtones together with dark wash underneath. The bell is penetrating and musical, but not overpowering. Byzance rides are especially unique in that they truly deliver the sought after "Made in Turkey" sound with their hand hammered profiles.', 'b_ride.jpg'); 

insert into products (category_id, product_name, price, quantity_remaining, description, image) values ('1', 'Meinl MB20 Heavy Bell Ride', '489.99', '32', 'Meinl’s Mb20 cymbals are a combination of superior materials, craftsmanship and strength, resulting in an aggressive sound. They are heavy cymbals which have been developed to meet all of the requirements for today’s hard hitting drummers playing loud music. When we decided it was time for a B20 hand hammered cymbal that could cut it in rock and metal, we designed Mb20. These cymbals combine musicality and volume in a range of medium-heavy and heavyweight models for maximum projection. Slightly dark and completely in your face, Mb20 is a great example of how we are repurposing hand hammered cymbals for todays music. The Mb20 22" Heavy Bell Ride cuts with a solid, large bell that produces a clear, dominant sound with full-bodied attack. Loud and powerful, yet musical.', 'mb20_ride.jpg');

insert into categories (category_name) values ('Sticks');

insert into products (category_id, product_name, price, quantity_remaining, description, image) values ('2', 'Vater 1A Wood Tip Drumsticks', '8.89', '12', 'Since the launch of their own stick line in 1990, Vater has quickly become one of the top stick manufacturers in the world today. The Vater factory produces over ten thousand sticks per day, which are shipped to over a thousand drum shops and music stores in thirty-five countries. Diameter: 37/64 Length: 16-7/8', 'vater_1a.jpg');

insert into products (category_id, product_name, price, quantity_remaining, description, image) values ('2', 'Vater 7A Nylon Tip Drumsticks', '9.36', '23', 'Since the launch of their own stick line in 1990, Vater has quickly become one of the top stick manufacturers in the world today. The Vater factory produces over ten thousand sticks per day, which are shipped to over a thousand drum shops and music stores in thirty-five countries. Diameter: 17/32 Length: 16', 'vater_7a.jpg');